### PR TITLE
Make sure we force push when the PR is updated.

### LINKED ISSUE #10: Sometimes fails to sync pull request branch after force push
On some occasions when I force push to a branch for a pull request it doesn't trigger a pipeline. On the LabHub console I see:

```
Error: Caught error handling PR: GitError { message: "Git error: \"cannot push non-fastforwardable reference\"" }
```

Does it need to force push branches from GitHub to GitLab? I am puzzled why this doesn't happen every time though.

### PR DESCRIPTION
**Pull request by brndnmtthws**
This resolves #10.

### CODE REVIEW

File: src/github.rs [hunk 1]
```diff
@@ -201,7 +201,7 @@ impl RepositoryExt for Repository {
         push_options.remote_callbacks(get_remote_callbacks(&config::CONFIG.gitlab));
 
         let refspec = format!(
-            "refs/heads/pr-{}/{}/{}:refs/heads/pr-{}/{}/{}",
+            "+refs/heads/pr-{}/{}/{}:refs/heads/pr-{}/{}/{}",
```
Comment (tdb) [inline src/github.rs]: Does the `+` need to be in front of the target? ie:

```
"refs/heads/pr-{}/{}/{}:+refs/heads/pr-{}/{}/{}"
```

Comment (brndnmtthws) [reply src/github.rs]: I don't believe so. The [git book says](https://git-scm.com/book/en/v2/Git-Internals-The-Refspec):

> The format of the refspec is, first, an optional +, followed by <src>:<dst>, where <src> is the pattern for references on the remote side and <dst> is where those references will be tracked locally. The + tells Git to update the reference even if it isn’t a fast-forward.

**Comment by brndnmtthws** [comment]
Tested with #12, appears to work as desired

🙂
